[package]
name = "papyrus_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.44" }
base64 = { version = "0.13.0" }
papyrus_storage = { path = "../papyrus_storage" }
futures-util = { version = "0.3.21" }
jsonrpsee = { version = "0.13.1", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.81" }
starknet_api = { git = "https://github.com/starkware-libs/starknet-api", rev = "4f1ca6327ebb9f64c9b6fec7651702bc95aa1282" }
thiserror = { version = "1.0.31" }
tokio = { version = "1.18.2", features = ["full", "sync"] }
tokio-stream = { version = "0.1.8" }
tracing = { version = "0.1.37" }
url = { version = "2.2.2" }

[dev-dependencies]
assert_matches = { version = "1.5.0" }
hex = { version = "0.4.3" }
jsonschema = { version = "0.16.1" }
papyrus_storage = { path = "../papyrus_storage", features = ["testing"] }
test_utils = { path = "../test_utils" }
starknet_api = { git = "https://github.com/starkware-libs/starknet-api", features = [
    "testing",
], rev = "4f1ca6327ebb9f64c9b6fec7651702bc95aa1282" }
web3 = { version = "0.18.0" }
indexmap = { version = "1.9.2", features = ["serde"] }
